### ISSUE TITLE
CSS optimieren für Widget-Größen

### ISSUE THREAD

**Issue by stritti** [stritti/covid-ampel-widget#12]
Anzeige der Daten für unterschiedliche Widget-Größen optimieren: 
https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/widgets

**Comment by 4ndre4s** [comment]
Es wäre super wenn es für Android ein 1x1 oder 2x2 Widget gäbe, um direkt die Infektionszahlen (mit Hintergrundfarbe) zu sehen, ohne dass der halbe Homescreen vom Widget versperrt ist.

**Comment by stritti** [comment]
Was sind das für Pixel-Abmessungen?

**Comment by 4ndre4s** [comment]
Ich schau es mir an :)

**Comment by stritti** [comment]
@4ndre4s kannst du mal probieren, ob das für Android auch so passt?

**Comment by 4ndre4s** [comment]
Passt, vielen Dank und sorry für die späte Antwort...
