### ISSUE TITLE
Share current Incidence

### ISSUE THREAD

**Issue by stritti** [stritti/covid-ampel-widget#25]
Possibly by using https://github.com/GabrielBibiano/vue-navigator-share

**Comment by 4ndre4s** [comment]
Soll das Teilen nur über die Webseite oder direkt aus dem Widget heraus möglich sein?

**Comment by stritti** [comment]
Da habe ich mir noch keine genauen Gedanken gemacht. Was denkst du?

**Comment by 4ndre4s** [comment]
Generell steht die Share Api fast nur auf Mobilgeräten zur Verfügung. Ich habe sie jetzt so integriert, dass sie beim Klick auf den Inzidenzwert (p.cases) getriggert wird. Das ist denke ich nicht der schönste Weg, allerdings kann die grafische Umsetzung leicht abgeändert werden 😃

**Comment by stritti** [comment]
Ja, stimmt, das macht vermutlich nur mobil Sinn.  
Hey cool! Schaue ich mir an. 
Ja ich denke da könnte man einen Share-Knopf spendieren, den man in den Homes-Screen-Widgets dann nicht sieht.
