### ISSUE TITLE
Inzidenz wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by 4ndre4s** [stritti/covid-ampel-widget#27]
**Aktuelles Verhalten**
Öffnet man die Seite des Ampel Widgets, erscheint eine Fehlermeldung. Auch eine Änderung des Landkreises liefert das gleiche Problem.

![image](https://user-images.githubusercontent.com/25303707/104582808-a630d780-5660-11eb-9141-c3cc9619b4c4.png)

**Erwartetes Verhalten**
Öffnet man die Seite des Ampel Widgets, sollte eigentlich die 7-Tage Inzidenz des jeweiligen Landkreises angezeigt werden.

**Möglicher Ursprung des Problems**
Die URL mit der die Daten des RKI abgefragt werden, scheint sich geändert zu haben:
Der Aufruf von 
`https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=OBJECTID%20in%20(1)&outFields=objectId,last_update,cases7_per_100k,EWZ,BEZ,GEN,IBZ&returnGeometry=false&f=json`

liefert als Antwort 

`{"error":{"code":400,"message":"Invalid URL","details":["Invalid URL"]}}`

**Comment by 4ndre4s** [comment]
Update: Die URL des RKI liefert bei Aufruf im Browser folgende Daten:

**Comment by 4ndre4s** [comment]
Liegt wahrscheinlich an der API des RKI.

**Comment by stritti** [comment]
Scheint ein Problem beim RKI zu sein. Das Scriptable-Widget hat auch das Problem: https://github.com/rphl/corona-widget/issues/118

Warten wir mal ab ...
