### ISSUE TITLE
Weißer Balken am oberen Bildschirmrand

### ISSUE THREAD

**Issue by 4ndre4s** [stritti/covid-ampel-widget#38]
![image](https://user-images.githubusercontent.com/25303707/105906985-b1064780-6024-11eb-93fb-193b68e8eb94.png)

**Comment by stritti** [comment]
Den habe ich schon mehrfach gesucht, bin ihm aber noch nicht auf die Spur gekommen. Es ist auf jeden Fall die Hintergrundfarbe der Seite (im Dark mode ist der Strich schwarz).

**Comment by 4ndre4s** [comment]
Danke für den schnellen Fix!
