### ISSUE TITLE
Hinweis zu den Regeln für die Stufen

### ISSUE THREAD

**Issue by stritti** [stritti/covid-ampel-widget#8]
Eventuell dezente Verlinkung zu den Regeln für die verschiedenen Stufen

**Comment by 4ndre4s** [comment]
An sich eine sehr gute Idee, allerdings sind die Stufen momentan (im Lockdown) nicht relevant (Issue wurde ja bereits im Oktober erstellt) und die einzelnen Bundesländer haben unterschiedliche Regelungen zu den Stufen, oder?

**Comment by stritti** [comment]
Ja das stimmt. Es ändert sich auch ständig etwas.

Eventuell könnte man abhängig vom Landkreis die betreffenden Seiten des Bundeslandes anzeigen.

Dieses könnte jedoch mit der Idee mehrere Landkreise anzuzeigen kollidieren.
