### ISSUE TITLE
Automatische Geolokalisierung

### ISSUE THREAD

**Issue by stritti** [stritti/covid-ampel-widget#9]
Wenn es der Browser unterstützt über die Geolocation den passenden Landkreis automatisch auswählen.

**Comment by 4ndre4s** [comment]
Zwangsläufig muss hierfür eine Drittanbieter API wie z.B. Google Geocoding verwendet werden, oder?

**Comment by stritti** [comment]
Die API vom RKI hat auch GEO-Daten mit welcher z. B. die Landkarte im Dashboard erzeugt wird.
Das Scriptable-Script kann übrigens diese Auflösung bereits.

**Comment by 4ndre4s** [comment]
Ah perfekt, ich schau es mir an; danke für den Hinweis!
